### ISSUE TITLE
Problems at the beginning and at the end of chromatograms

### ISSUE THREAD

**Issue by ctapobep** [tvijverb/BEADS_Baseline_correction#1]
I tried Python implementation and I [couldn't get the answer there](https://github.com/hsiaocy/Beads/issues/1#issuecomment-429565089), but I guess it shouldn't be different from this one. 

On one of the chromatograms that I tried there are artifacts at the beginning and at the end. I don't understand the math behind the algorithm yet, so was wondering if this is a known limitation or this is configurable:

![fc09](https://user-images.githubusercontent.com/702510/47027803-c8c9a280-d170-11e8-95d8-38ea32681085.png)

Parameters that I used:

```
    fc = .8
    d = 1
    r = 6
    amp = 0.8
    lam0 = 0.5 * amp
    lam1 = 5 * amp
    lam2 = 4 * amp
```

**Comment by tvijverb** [comment]
My understanding of the mathematics isn't perfect either. You could contact the authors of the original paper and see if they are inclined to fully answer your questions. That being said, I noticed a similar trend with my experiments. Fitting a parabola over the data to force the start & end of your chromatogram to 0 might solve your problems as wel.
